import { NextPage } from "next";
import Head from "next/head";

const HomePage: NextPage = () => (
  <div>
    <Head>
      <title>Album Liner Notes</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  </div>
);

export default HomePage;
